//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace week4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit
    {
        public int Id { get; set; }
        public string UnitName { get; set; }
        public string Description { get; set; }
        public int studentId { get; set; }
    
        public virtual student student { get; set; }
    }
}
